server {
    listen 80;
    server_name 46.224.190.225;

    # Frontend
    location / {
        root /opt/pertosa-rag/src/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Metrics
    location /metrics {
    proxy_pass http://127.0.0.1:8000/metrics;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    }

    # API
    location /ask {
        proxy_pass http://127.0.0.1:8000/ask;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding on;
    }
}
