server {
    server_name open-pertosa.it;

    # Frontend
    location / {
        root /opt/pertosa-rag/src/frontend;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Metrics
    location /metrics {
    proxy_pass http://127.0.0.1:8000/metrics;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    }

    # DOCUMENTI
    location /docs/ {
        alias /opt/pertosa-rag/data/raw/;
        add_header Content-Disposition "inline";
        types { application/pdf pdf; }
        default_type application/pdf;
    }

    # API
    location /ask {
        proxy_pass http://127.0.0.1:8000/ask;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_cache off;
        chunked_transfer_encoding on;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/open-pertosa.it/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/open-pertosa.it/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = open-pertosa.it) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name open-pertosa.it;
    return 404; # managed by Certbot


}